name: daily
description: New prompt every day.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Essentials
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  #Data management
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.5
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.2
  flutter_twitter_login: ^1.1.0
  picker: ^1.0.6
  path_provider: ^2.0.1
  http: ^0.13.3
  share:
    git:
      url: git://github.com/himanshusharma89/plugins.git
      path: packages/share

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
