name: daily
description: New prompt every day.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Essentials
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  #Data management
  shared_preferences: ^0.5.6
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.5
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.2
  picker: ^1.0.6
  path_provider: ^2.0.1
  provider: ^5.0.0
  http: ^0.13.3
  share:
    git:
      url: git://github.com/himanshusharma89/plugins.git
      path: packages/share

  #Utilities
  image: ^3.0.8

  #User interface
  page_transition: ^1.1.7+3
  font_awesome_flutter: ^9.1.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - lib/assets/welcome/welcome_carouselOne.png
      - lib/assets/welcome/welcome_carouselTwo.png
      - lib/assets/welcome/welcome_carouselThree.png
      - lib/assets/welcome/welcome_corner.png
      - lib/assets/auth/auth_centerPiece.png
      - lib/assets/forgotPassword/forgotPassword_centerPiece.png
      - lib/assets/home/home_carouselOne.png
      - lib/assets/home/home_carouselTwo.png
      - lib/assets/home/home_carouselThree.png
      - lib/assets/home/home_carouselFour.png
      - lib/assets/home/home_carouselFive.png
      - lib/localizations/en.json
      - lib/localizations/es.json
      - lib/localizations/fr.json
