name: daily
description: New prompt every day.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Essentials
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  auto_route: ^3.2.4

  #Firebase
  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14
  cloud_firestore_web: ^2.6.14
  firebase_storage: ^10.2.15
  firebase_storage_web: ^3.2.14
  firebase_auth: ^3.3.17
  firebase_auth_web: ^3.3.14

  #Management
  file_picker: ^4.5.1
  universal_io: ^2.0.4
  path_provider: ^2.0.1
  provider: ^5.0.0
  http: ^0.13.3
  shared_preferences: ^0.5.6
  cached_network_image: ^3.2.0
  dot_navigation_bar: ^1.0.1+3
  camera: ^0.9.4+11
  image: ^3.1.1

  #User interface
  page_transition: ^1.1.7+3
  font_awesome_flutter: ^9.1.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7

flutter_icons:
  android: "icon" 
  ios: true
  image_path: "lib/assets/launcher/icon.png"

flutter:
  uses-material-design: true

  assets:
      - lib/legal/documents/privacyPolicy_01182022.txt
      - lib/legal/documents/termsAndConditions_01182022.txt
      - lib/assets/launcher/icon.png
      - lib/assets/launcher/icon_noBackground.png
      - lib/assets/auth/web/auth_centerPiece_dark.jpg
      - lib/assets/auth/web/test.jpg
      - lib/assets/auth/web/auth_centerPiece_light.jpg
      - lib/assets/auth/mobile/auth_centerPiece_dark.jpg
      - lib/assets/auth/mobile/auth_centerPiece_light.jpg
      - lib/localizations/zh.json
      - lib/localizations/de.json
      - lib/localizations/en.json
      - lib/localizations/es.json
      - lib/localizations/fi.json
      - lib/localizations/fr.json
      - lib/localizations/it.json
      - lib/localizations/ja.json
      - lib/localizations/pl.json
      - lib/localizations/ru.json
